### ISSUE TITLE
ProcessQueueMessage: Client.ServerUnauthorizedAccessException: Access denied

### ISSUE THREAD

**Issue by johnbrice** [SharePoint/PnP#1609]
Hi all

I have provisioned Async Site collection provisioning.

I have everything deployed, add in, webjob. However I seem to be missing a permission somewhere and cant work out where. Really hope someone can help.

Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Exception while executing function: Functions.ProcessQueueMessage ---> Microsoft.SharePoint.Client.ServerUnauthorizedAccessException: Access denied. You do not have permission to perform this action or access this resource.
 at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
 at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
 at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryToServer(ChunkStringBuilder sb)
 at Microsoft.SharePoint.Client.ClientRequest.ExecuteQuery()
 at Microsoft.SharePoint.Client.ClientRuntimeContext.ExecuteQuery()
 at Microsoft.SharePoint.Client.ClientContext.ExecuteQuery()
 at Provisioning.Cloud.Async.WebJob.Common.SiteRequestManager.SiteURLAlreadyInUse(ClientContext

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
