### ISSUE TITLE
list.RootFolder null when attempting to upload first file. 

### ISSUE THREAD

**Issue by igorpacheco** [SharePoint/PnP#1688]
####Which PnP repository should you use to report the issue?####
- PnP Samples - https://github.com/OfficeDev/PnP

![capture](https://user-images.githubusercontent.com/31022080/29298338-217f0814-81a6-11e7-96ab-3e70ebf9d721.PNG)

#### Category
[X] Bug
[ ] Enhancement

#### Environment
[X] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
ApplyBranding 

#### Steps to Reproduce
- Run the solution on Visual Studio. 
- Log with my Global admin account 

#### Error
(BrandingHelper.cs) ln:152: list.RootFolder Exception Unhandled 
System.NullReferenceException: 'Object reference not set to an instance of an object.'

System.NullReferenceException occurred
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Contoso.Branding.ApplyBranding.Console
  StackTrace:
   at Contoso.Branding.ApplyBranding.BrandingHelper.EnsureFolder(Web web, String listUrl, String folderUrl, Folder parentFolder) in C:\Users\IgorPacheco\Documents\Innodev\Projects\PnP-master\PnP-master\Samples\Branding.ApplyBranding\Branding.ApplyBranding.Console\BrandingHelper.cs:line 152
   at Contoso.Branding.ApplyBranding.BrandingHelper.EnsureFolder(Web web, String listUrl, String folderUrl) in C:\Users\IgorPacheco\Documents\Innodev\Projects\PnP-master\PnP-master\Samples\Branding.ApplyBranding\Branding.ApplyBranding.Console\BrandingHelper.cs:line 210
   at Contoso.Branding.ApplyBranding.BrandingHelper.EnsureFolders(Web web, String filePath, String fileFolder, String fileName) in C:\Users\IgorPacheco\Documents\Innodev\Projects\PnP-master\PnP-master\Samples\Branding.ApplyBranding\Branding.ApplyBranding.Console\BrandingHelper.cs:line 214
   at Contoso.Branding.ApplyBranding.BrandingHelper.UploadFile(ClientContext clientContext, String name, String folder, String path) in C:\Users\IgorPacheco\Documents\Innodev\Projects\PnP-master\PnP-master\Samples\Branding.ApplyBranding\Branding.ApplyBranding.Console\BrandingHelper.cs:line 18
   at Contoso.Branding.ApplyBranding.Program.UploadFiles(ClientContext clientContext, XElement branding, DateTime lastRun) in C:\Users\IgorPacheco\Documents\Innodev\Projects\PnP-master\PnP-master\Samples\Branding.ApplyBranding\Branding.ApplyBranding.Console\Program.cs:line 106
   at Contoso.Branding.ApplyBranding.Program.Main(String[] args) in C:\Users\IgorPacheco\Documents\Innodev\Projects\PnP-master\PnP-master\Samples\Branding.ApplyBranding\Branding.ApplyBranding.Console\Program.cs:line 64

**Comment by igorpacheco** [comment]
![capture](https://user-images.githubusercontent.com/31022080/29298399-72cb67bc-81a6-11e7-8313-e23cdea57b81.PNG)

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
