### ISSUE TITLE
PnP Starter Intranet v2.0 update #1691

### ISSUE THREAD

**Issue by pakonawala** [SharePoint/PnP#1695]
Hi Frank nice sample you have there (PnP Starter Intranet v2.0) i tried to install you latest release from scratch and having sass loader issues. I tried all i could to get it working but no luck. Please look at the error below. This all happens when trying to build the code-Webpack command

Child extract-text-webpack-plugin:
[0] ..//css-loader!..//resolve-url-loader!../~/sass-loader/lib/loader.js?{"sourceMap":true}!./styles/css/icscalendargenerator.scss 3.06 kB {0} [built] [failed] [1 error]

ERROR in ../~/css-loader!../~/resolve-url-loader!../~/sass-loader/lib/loader.js?{"sourceMap":true}!./styles/css/icscalendargenerator.scss
Module build failed: Error: ENOENT: no such file or directory, scandir 'C:\Users\vincent.nawala\Documents\Office 365\Web Part\Homepage\app\node_modules\node-sass\vendor'
    at Error (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at Object.getInstalledBinaries (C:\Users\vincent.nawala\Documents\Office 365\Web Part\Homepage\app\node_modules\node-sass\lib\extensions.js:123:13)
    at foundBinariesList (C:\Users\vincent.nawala\Documents\Office 365\Web Part\Homepage\app\node_modules\node-sass\lib\errors.js:20:15)
    at foundBinaries (C:\Users\vincent.nawala\Documents\Office 365\Web Part\Homepage\app\node_modules\node-sass\lib\errors.js:15:5)
    at Object.module.exports.missingBinary (C:\Users\vincent.nawala\Documents\Office 365\Web Part\Homepage\app\node_modules\node-sass\lib\errors.js:45:5)
    at module.exports (C:\Users\vincent.nawala\Documents\Office 365\Web Part\Homepage\app\node_modules\node-sass\lib\binding.js:15:30)
    at Object.<anonymous> (C:\Users\vincent.nawala\Documents\Office 365\Web Part\Homepage\app\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\vincent.nawala\Documents\Office 365\Web Part\Homepage\app\node_modules\sass-loader\lib\loader.js:3:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at loadLoader (C:\Users\vincent.nawala\Documents\Office 365\Web Part\Homepage\app\node_modules\loader-runner\lib\loadLoader.js:13:17)
    at iteratePitchingLoaders (C:\Users\vincent.nawala\Documents\Office 365\Web Part\Homepage\app\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at iteratePitchingLoaders (C:\Users\vincent.nawala\Documents\Office 365\Web Part\Homepage\app\node_modules\loader-runner\lib\LoaderRunner.js:165:10)
    at C:\Users\vincent.nawala\Documents\Office 365\Web Part\Homepage\app\node_modules\loader-runner\lib\LoaderRunner.js:173:18
    at loadLoader (C:\Users\vincent.nawala\Documents\Office 365\Web Part\Homepage\app\node_modules\loader-runner\lib\loadLoader.js:36:3)
    at iteratePitchingLoaders (C:\Users\vincent.nawala\Documents\Office 365\Web Part\Homepage\app\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at iteratePitchingLoaders (C:\Users\vincent.nawala\Documents\Office 365\Web Part\Homepage\app\node_modules\loader-runner\lib\LoaderRunner.js:165:10)

Thanks

**Comment by FranckyC** [comment]
Hi @pakonawala. What version of webpack do you have globally? This sample works with the 2.4.1 webpack version. Try also to update your node-sasss (4.5.3) and sass-loader versions (6.0.3).

**Comment by FranckyC** [comment]
@pakonawala did you retry the installation with mentioned version above?

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
