### ISSUE TITLE
Provisioning Schema intermittent errors while applying template

### ISSUE THREAD

**Issue by ashavibapat** [SharePoint/PnP#1723]
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core
[ ] Bug
[ ] Office 365 / SharePoint Online
#### Expected or Desired Behavior
Provisioning succeeds .
#### Observed Behavior
For one of our customers we have used the PNP Provisioning framework to create new site collections and artifacts.
Everything works smoothly, but intermittently we are seeing 2 errors  as below on PROD and also on lower environments.
This works fine, if same template is applied again.
We also raised premier tickets ,but they were not able to get to the logs with the correlationids provided.
Do you have any insights on these?
Attached are the templates we are using. 
1.	Project site template
We're having trouble with SharePoint storage. ----------- Stack Trace ------------- :    at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream) 
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse() 
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryToServer(ChunkStringBuilder sb) 
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQuery() 
   at Microsoft.SharePoint.Client.ClientRuntimeContext.ExecuteQuery() 
   at Microsoft.SharePoint.Client.ClientContext.ExecuteQuery() 
   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryImplementation(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay) in F:\tfsagent\_work\34\s\BDO.GP.SPE\OfficeDevPnP\Core\OfficeDevPnP.Core\Extensions\ClientContextExtensions.cs:line 145 
   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryRetry(ClientRuntimeContext clientContext) in F:\tfsagent\_work\34\s\BDO.GP.SPE\OfficeDevPnP\Core\OfficeDevPnP.Core\Extensions\ClientContextExtensions.cs:line 64 
   at Microsoft.SharePoint.Client.BrandingExtensions.SetThemeByUrl(Web web, String paletteServerRelativeUrl, String fontServerRelativeUrl, String backgroundServerRelativeUrl, Boolean resetSubsitesToInherit, Boolean updateRootOnly) in F:\tfsagent\_work\34\s\BDO.GP.SPE\OfficeDevPnP\Core\OfficeDevPnP.Core\Extensions\BrandingExtensions.cs:line 278  
2.	Team site template.
: The parent content type specified by content type identifier 0x0108003365C4474CAE8C42BCE396314E88E51F does not exist.
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryToServer(ChunkStringBuilder sb)
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientRuntimeContext.ExecuteQuery()
  at Microsoft.SharePoint.Client.ClientContext.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryImplementation(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay) in F:\tfsagent\_work\34\s\BDO.GP.SPE\OfficeDevPnP\Core\OfficeDevPnP.Core\Extensions\ClientContextExtensions.cs:line 145
   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryRetry(ClientRuntimeContext clientContext) in F:\tfsagent\_work\34\s\BDO.GP.SPE\OfficeDevPnP\Core\OfficeDevPnP.Core\Extensions\ClientContextExtensions.cs:line 64
   at Microsoft.SharePoint.Client.FieldAndContentTypeExtensions.CreateContentType(Web web, String name, String description, String id, String group, ContentType parentContentType) in F:\tfsagent\_work\34\s\BDO.GP.SPE\OfficeDevPnP\Core\OfficeDevPnP.Core\Extensions\FieldAndContentTypeExtensions.cs:line 1373
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectContentType.CreateContentType(Web web, ContentType templateContentType, TokenParser parser, FileConnectorBase connector, PnPMonitoredScope scope, List`1 existingCTs, List`1 existingFields, Boolean isNoScriptSite) in F:\tfsagent\_work\34\s\BDO.GP.SPE\OfficeDevPnP\Core\OfficeDevPnP.Core\Framework\Provisioning\ObjectHandlers\ObjectContentType.cs:line 290
Thanks,
Ashwini

**Comment by spdevdocs** [comment]
We closed this issue as it had no activity within the last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize for any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
