### ISSUE TITLE
NullReferenceException in GetProvisioningTemplate for sites with multiple languages

### ISSUE THREAD

**Issue by ls-mze** [SharePoint/PnP#1775]
####Which PnP repository should you use to report the issue?####
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core

#### Category
[ x] Bug
[ ] Enhancement

#### Environment
[ x] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
Extracting a template from a site should work as expected, but does no longer since the last update.

#### Observed Behavior
Extracting a template from a site with multiple languages produces a NullReferenceException when trying to get the localizations.
The exception is only thrown when PersistMultiLanguageResources is set to true, and only in the current release 2.25.1804.1 of SharePointPnPCoreOnline.
The last two versions 2.24.1803 and  2.23.1802 both seem to work correctly. If either the target site is not multilingual or PersistMultiLanguageResources is false, no exception will be thrown.

StackTrace:
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.Extensions.UserResourceExtensions.SaveResourceValues(ProvisioningTemplate template, ProvisioningTemplateCreationInformation creationInfo)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectLocalization.ExtractObjects(Web web, ProvisioningTemplate template, ProvisioningTemplateCreationInformation creationInfo)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.GetRemoteTemplate(Web web, ProvisioningTemplateCreationInformation creationInfo)
   at Microsoft.SharePoint.Client.WebExtensions.GetProvisioningTemplate(Web web, ProvisioningTemplateCreationInformation creationInfo)
   at GetTemplateTest.Program.Main(String[] args) in C:\Workspaces\_temp\GetTemplateTest\GetTemplateTest\Program.cs:line 31

#### Steps to Reproduce
- Create a new team site in SharePoint Online.
- Add any number of additional languages under Site Settings > Site Administration > Language Settings
- Create a solution in Visual Studio and add SharePointPnPCoreOnline Version 2.25.1804.1 via NuGet.
- Try to extract a template from the site, PersistMultiLanguageResources must be true (see example code).

Example code:
using (var ctx = new ClientContext(url))
{
	ctx.Credentials = creds;
	ctx.Load(ctx.Web);
	ctx.ExecuteQuery();
	var ptci = new OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ProvisioningTemplateCreationInformation(ctx.Web);
	ptci.PersistMultiLanguageResources = true;
	ptci.ProgressDelegate += (msg, step, total) => { Console.WriteLine($"{step}|{total} - {msg}"); };
	var template = WebExtensions.GetProvisioningTemplate(ctx.Web, ptci);
}

**Comment by spdevdocs** [comment]
We closed this issue as it had no activity within the last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize for any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
