### ISSUE TITLE
Can't create a new team site inside organization with Chinese region

### ISSUE THREAD

**Issue by isxaker** [SharePoint/PnP#1778]
Hi dev team.
I've cought something like a bug.
Actually I can't create a new team site inside organization with Chinese region.
[SO](https://sharepoint.stackexchange.com/questions/240920/cant-create-a-new-time-site-inside-organization-with-chinese-region)

I try to create a new team site in an organization with Chinese region.
And my(code c# or powershell) always gives me the same error.
(However team site is created after execution)

   ```
 New-PnPSite : {"d":{"CreateGroupEx":{"__metadata":{"type":"Microsoft.SharePoint.Portal.GroupSiteInfo"},"DocumentsUrl":n
    ull,"ErrorMessage":null,"GroupId":"267a6743-a4c4-4f41-981d-9783c56d4852","SiteStatus":1,"SiteUrl":null}}}
    At line:1 char:16
    + ... amSiteUrl = New-PnPSite -Type TeamSite -Title "displayName" -Alias "q ...
    +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : WriteError: (:) [New-PnPSite], Exception
        + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.NewSite
```

But it's interesting that I'm able to create a team site inside another organization which has default region with the same code.

c# code:
    ```
var targetTenantUrl = "https://mytenant.sharepoint.cn/";
    
    using (var context = new ClientContext(targetTenantUrl))
    {
        context.Credentials = appropiateCredentials;
       
        var teamContext = await context.CreateSiteAsync(
            new TeamSiteCollectionCreationInformation
            {
                Alias = "mymodernteamsite",
                DisplayName = "displayName",
                Description = "description",
                Classification = "classification",
                IsPublic = true
            });
        teamContext.Load(teamContext.Web, w => w.Url);
        teamContext.ExecuteQueryRetry();
        Console.WriteLine(teamContext.Web.Url);
    }
```

ps code:

   ```
 Connect-PnPOnline "https://mytenant.sharepoint.cn/"
           
    $teamSiteUrl = New-PnPSite -Type TeamSite -Title "displayName" -Alias "mymodernteamsite" -Description "description" -IsPublic -Classification "classification" 
```

#### Category
[ ] Bug

#### Environment
[ ] Office 365 / SharePoint Online
latest pnp and csom

**Comment by isxaker** [comment]
at OfficeDevPnP.Core.Sites.SiteCollection.<CreateAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContextExtensions.<CreateSiteAsync>d__17.MoveNext()

 at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()

**Comment by spdevdocs** [comment]
We closed this issue as it had no activity within the last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize for any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
