### ISSUE TITLE
Apply Template fails while updating an internal column called Comment Count for a library

### ISSUE THREAD

**Issue by pras01091981** [SharePoint/PnP#1811]
#### Category
[x] Bug
[ ] Enhancement

#### Environment
[x] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 

#### Expected or Desired Behavior
PnP Commands to apply a custom template (Apply-PnPProvisioningTemplate) will apply all the customizations from the extracted xml template to a site.
We are using the August 2018 Intermediate 1 release but see this error with all the below versions:
- 2.28.1807.0
- 2.22.1801.0
- 2.17.1708.1 (It worked with this version before (till May 2018) but does not anymore and throws the same error)

#### Observed Behavior
It fails while updating a SharePoint Internal Column called "Comment Count" with internal name as "_CommentCount" while applying the custom template. We get the below error when the trace logs are enabled:

PowerShell_ISE.exe Error: 0 : 2018-09-04 21:46:37.3504	[List instances]	[11]	[Error]	Updating field d307dff3-340f-44a2-9f4b-fbfe1ba07459 failed: File Not Found. :    at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryToServerAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientRuntimeContext.<ExecuteQueryAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContext.<ExecuteQueryAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientObjectExtensions.<EnsurePropertyImplementation>d__5`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientObjectExtensions.EnsureProperty[T,TResult](T clientObject, Expression`1 propertySelector)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.Utilities.FieldUtilities.FixLookupField(String fieldXml, Web web)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectListInstance.UpdateField(Web web, ListInfo listInfo, Guid fieldId, XElement templateFieldElement, Field existingField, PnPMonitoredScope scope, TokenParser parser, String originalFieldXml)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectListInstance.ProcessFields(Web web, TokenParser parser, PnPMonitoredScope scope, ListInfo listInfo)	795799ms	3cc6ee20-edec-4241-aa4c-82f6306bdf00

The field is defined as below in the extracted xml template (xml that is generated when we use the Get-PnPProvisioningTemplate command):

`<pnp:Fields>
            <Field ID="{d307dff3-340f-44a2-9f4b-fbfe1ba07459}" Name="_CommentCount" DisplaceOnUpgrade="TRUE" ReadOnly="TRUE" ShowInFileDlg="FALSE" Type="Lookup" DisplayName="Comment count" List="Docs" FieldRef="ID" ShowField="CommentCount" JoinColName="DoclibRowId" JoinRowOrdinal="0" JoinType="INNER" SchemaVersion="16.0.139.0" RecreateIfMissing="TRUE" SourceID="http://schemas.microsoft.com/sharepoint/v3" StaticName="_CommentCount" FromBaseType="TRUE" Sealed="FALSE" Version="4" />
</pnp:Fields>`

* There are other fields there as well within the pnp:Fields tags but are not mentioned here for simplicity.
#### Steps to Reproduce

- Extract the template site with library which has the in-built Column Count column using the Get-PnPProvisioningTemplate command into an xml file.

- Use the Apply-PnPProvisioningTemplate command to apply the template.

- During the apply template process, the process errors out with the error as stated above.

Thanks.

**Comment by asith-w** [comment]
+1
